{
	general(visitorId: "", query: "$query") {
		visitorId
		bestMatch {
			title
			id
			type
			duration
			thumbnails {
				url
			}
			artists {
				name
			}
		}
		tracks {
			songs {
				title
				id
				duration
				artists {
					name
				}
				thumbnails {
					url
				}
			}
			continuation {
				params
				query
			}
		}
	}
}
